### ISSUE TITLE
Could you build a release?

### ISSUE THREAD

**Issue by link-fgfgui** [QAQQL/Wuthering-Waves-wish-export#1]
If you build a release, it will be easy for users to use the programe.

**Comment by QAQQL** [comment]
这个软件刚刚起步,我正在学习Electron的结构,正如Commit的内容,该项目还存在很多bug,不建议打包给用户
我会在下个星期内完善该项目,届时将发布release,还请您再等待一下

This software is just getting started, I am learning the structure of the Electron, as Commit content, the project there are still many bugs, not recommended to package to the user 
I will improve the project in the next week, when the release will be released, please wait a little longer.

**Comment by KalimiaChen** [comment]
试了一下（文件夹选择为Wuthering Waves\Wuthering Waves Game），抽数统计无误，我的卡池数据（总抽数/4星/5星）：
角色活动： 23 3 0
武器活动： 0
角色常驻： 41 6 0
武器常驻：20 3 0
新手：10 0 1
新手自选： 30 4 1
感恩定向：0

但饼图实际只显示了角色活动，角色常驻，武器常驻这三个，结果分别为
角色活动： 23 3 0
角色常驻：41 6 0
武器常驻：20 3 0

把两个出5星的池子跳过了。

**Comment by QAQQL** [comment]
setting.vue 的 hideNovice: false
即 设置中的隐藏新手抽卡记录关闭即可

**Comment by QAQQL** [comment]
更新数据暂时因为合并有bug,已经在commit中反映,等有空修复,暂时使用设置中的清空数据功能
