### ISSUE TITLE
it isn't working for me

### ISSUE THREAD

**Issue by Craken2** [QAQQL/Wuthering-Waves-wish-export#3]
Hello, i tried several times to export wishes but the sheet is empty 
![image](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/174210620/e283e100-e232-4655-8cee-b49e7c004999)
![image](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/174210620/8d03b51d-847a-4246-9c34-e2b5ae77c0a8)
and at the begin the soft opened a windows and as a title of it was "Wuthering Waves Game" then i have indicate where the game was installed and it started to search history but the soft stay blank same as the exported sheet.

**Comment by Megumism** [comment]
> Hello, i tried several times to export wishes but the sheet is empty ![image](https://private-user-images.githubusercontent.com/174210620/344427658-e283e100-e232-4655-8cee-b49e7c004999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDI5MjgsIm5iZiI6MTcxOTgwMjYyOCwicGF0aCI6Ii8xNzQyMTA2MjAvMzQ0NDI3NjU4LWUyODNlMTAwLWUyMzItNDY1NS04Y2VlLWI0OWU3YzAwNDk5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwMjU3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjFiNjdmMWMyMGZhY2VkM2IyOGVkNjFjY2U1YmFmZTFhNWQwNDI4NzZjNDQ0YTQ5N2M1NGQwN2IxYmVjOGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nivxrb6qn0vRn9eWu6ebOWxcTkcBPOAFoD_r-B2Wem4) ![image](https://private-user-images.githubusercontent.com/174210620/344427661-8d03b51d-847a-4246-9c34-e2b5ae77c0a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDI5MjgsIm5iZiI6MTcxOTgwMjYyOCwicGF0aCI6Ii8xNzQyMTA2MjAvMzQ0NDI3NjYxLThkMDNiNTFkLTg0N2EtNDI0Ni05YzM0LWUyYjVhZTc3YzBhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwMjU3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzI3MGNlZThiYTU4MWY1OTI0ZDhkNmI2YWJiMzcwMGMzMDcxYjA5NTgzZGNiMmQ5YmEzMGVkODk4M2YzMDU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pHWBnf_jbDDD2XF3CCti7BlR2xq0s7qOUCOiQ5UMtY8) and at the begin the soft opened a windows and as a title of it was "Wuthering Waves Game" then i have indicate where the game was installed and it started to search history but the soft stay blank same as the exported sheet.

Maybe it doesnt work just cause you r international server player? It works for me.

**Comment by QAQQL** [comment]
Can you provide me with the path you choose?
When you use the software, please open the game draw history.

**Comment by QAQQL** [comment]
The software is run by reading the website of the game draw card in the following file.
F:\Program Files\Wuthering Waves\Wuthering Waves Game\Client\Saved\Logs\Client.log

**Comment by Caelum008** [comment]
> Can you provide me with the path you choose? When you use the software, please open the game draw history.

which path should be used? because I tried it as well and the Client.log isn't being detected by the app.
![image](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/148611437/739197f1-2a18-4a5d-9e9b-953a1a8e9c0b)

**Comment by QAQQL** [comment]
选择到Wuthering Waves Game路径
例如
F:\Program Files\Wuthering Waves\Wuthering Waves Game

**Comment by Craken2** [comment]
> Can you provide me with the path you choose? When you use the software, please open the game draw history.

![image](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/174210620/d54c387b-97b3-4ff2-839f-2915eb81fab9)

**Comment by QAQQL** [comment]
I suggest you open Client.log and search with "https://xxxxxxxx/aki/gacha/index.html" and "/record? The data at the end of svr_id=xxxx "may be that the URL of the card drawing link of the international service is different, which leads to the regularization error.
If yes, please provide the URL.
Please hide your private data before transmission, as follows

https://aki-gm-resources.aki-game.com/aki/gacha/index.html#/record?svr_id=xxx&player_id=xxx&lang=zh-Hans&gacha_id=xxxx&gacha_type=1&svr_area=cn&record_id=xxxx&resources_id=xxxx

**Comment by QAQQL** [comment]
I really can't get it. I may read the following directory "F:\Program Files\Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\ThirdParty\KrPcSdk_Mainland\KRSDKRes\KRSDKWebView" by reading the chrome cache from the original project.

**Comment by Caelum008** [comment]
> I really can't get it. I may read the following directory "F:\Program Files\Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\ThirdParty\KrPcSdk_Mainland\KRSDKRes\KRSDKWebView" by reading the chrome cache from the original project.

![image](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/148611437/e3657f77-cef3-4053-a3b9-4b848d6cb692)

this one? which file?

**Comment by Caelum008** [comment]
> I suggest you open Client.log and search with "https://xxxxxxxx/aki/gacha/index.html" and end of "/record?svr_id=xxxx ",may be that the URL of the card drawing link of the international service is different, which leads to the regularization error. If yes, please provide the URL. Please hide your private data before transmission, as follows
> 
> https://aki-gm-resources.aki-game.com/aki/gacha/index.html#/record?svr_id=xxx&player_id=xxx&lang=zh-Hans&gacha_id=xxxx&gacha_type=1&svr_area=cn&record_id=xxxx&resources_id=xxxx

are you referring to the convene history URL? I didn't find mine on Client.log. instead, I found it on debug.log and it goes like this:
`https://aki-gm-resources-oversea.aki-game.net/aki/gacha/index.html#/record?svr_id=xxxxx&player_id=xxxxx&lang=en&gacha_id=xxxxx&gacha_type=1&svr_area=global&record_id=xxxxx&resources_id=xxxxx`

**Comment by QAQQL** [comment]
Version 1.0.3 has been submitted, please use it to see if the problem has been solved.

**Comment by Caelum008** [comment]
> Version 1.0.3 has been submitted, please use it to see if the problem has been solved.

it finally worked on my end. NA server. thank you so much!

**Comment by QAQQL** [comment]
怪了,我刚刚测试没问题啊
![图片](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/51136763/6ea33a9a-d896-4a72-9fb9-f32372b49002)

**Comment by QAQQL** [comment]
您清空一下 本软件目录下的userData下的文件\
重置一下配置试试呢

**Comment by Craken2** [comment]
![image](https://github.com/QAQQL/Wuthering-Waves-wish-export/assets/174210620/667ece1b-93a3-4c1d-a62c-93240b7bb2c1)
hello, i replaced by the 1.0.3, it load the data then the window become full white, then when i close the soft, run it again the window is still white

**Comment by QAQQL** [comment]
I tried to download the Release version to reproduce your problem, but it failed.
![图片](https://github.com/user-attachments/assets/44a47ef4-70ab-4e2f-b85e-53d16a6985ef)
![图片](https://github.com/user-attachments/assets/4ce13639-6410-4e4f-8f8e-3e8ac8c803c1)
If you don't mind, could you send the zip compressed document of your userdata folder to my email?(273641837@qq.com)

**Comment by QAQQL** [comment]
Do you open the software and blank it, or do you blank it after running it?

**Comment by Craken2** [comment]
the soft itself become blank i don't do it myself. 
it start blank when it is launched a second time or it become blank the first time after the data loading
i can show you what is inside but i will not send any mail sorry.
![image](https://github.com/user-attachments/assets/59184d0a-547d-4583-a381-5340f7986850)
![image](https://github.com/user-attachments/assets/9ecc07e0-e162-4405-8f6b-2e923a5ea7df)

**Comment by QAQQL** [comment]
Sorry, I can't reproduce your question.
I can't catch your international service data format for the time being, and may not be able to solve your problem for the time being.

**Comment by xKosar** [comment]
It works fine in Chinese, but if you change language to English it becomes blank

> Sorry, I can't reproduce your question. I can't catch your international service data format for the time being, and may not be able to solve your problem for the time being.

**Comment by QAQQL** [comment]
Thank you for your feedback.
Let me check the lack of json entries in other languages.

**Comment by Caelum008** [comment]
> ![image](https://private-user-images.githubusercontent.com/174210620/347779145-667ece1b-93a3-4c1d-a62c-93240b7bb2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzE4NjcsIm5iZiI6MTcyMTg3MTU2NywicGF0aCI6Ii8xNzQyMTA2MjAvMzQ3Nzc5MTQ1LTY2N2VjZTFiLTkzYTMtNGMxZC1hNjJjLTkzMjQwYjdiYjJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwMTM5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTA0MDNiYjVhMGMzODc1MDVjZjdiNGJiZGIxODAxODlmMzZiYjUzMTM1ZWNhNzA3NTk2ZDIxY2M3YzNhOGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5NYjByONtZuLSxW8fUOOSgnvh7ty4Pm3ojNvOvSvizA) hello, i replaced by the 1.0.3, it load the data then the window become full white, then when i close the soft, run it again the window is still white on the gacha-list-xxxxxxx.json file it seems have well reported all wishes but how to export into excel table when the soft is full white ? 😥

@QAQQL this happened to me when I included the Beginner's Convene History in the capture. it's fine when I leave it off though.

**Comment by QAQQL** [comment]
Please help me summarize the card pool names of the novice pool except the national service, thank you.
At present, the error is found because the keyword of blocking novice pool is Chinese, which leads to the error.

**Comment by Caelum008** [comment]
> Please help me summarize the card pool names of the novice pool except the national service, thank you. At present, the error is found because the keyword of blocking novice pool is Chinese, which leads to the error.

sure. what do I need to do to obtain them? do I just screenshot them and send them here?

**Comment by QAQQL** [comment]
> > Please help me summarize the card pool names of the novice pool except the national service, thank you. At present, the error is found because the keyword of blocking novice pool is Chinese, which leads to the error.
> 
> sure. what do I need to do to obtain them? do I just screenshot them and send them here?

Yes, thank you

**Comment by QAQQL** [comment]
v1.0.4
I changed the logic to card pool id, and it can run normally, but i18n is still necessary.

**Comment by Caelum008** [comment]
> v1.0.4 I changed the logic to card pool id, and it can run normally, but i18n is still necessary.

where can I find i18n so I can send a screenshot to you.

**Comment by QAQQL** [comment]
Now, I have added an English translation, so I suggest you test it. I will slowly collect other languages, thank you.

**Comment by Caelum008** [comment]
> Now, I have added an English translation, so I suggest you test it. I will slowly collect other languages, thank you.

trying it now. I'm gonna send a feedback once I have tried.

**Comment by Caelum008** [comment]
update: it worked. it managed to capture the beginner banners without a hitch. thank you!

**Comment by QAQQL** [comment]
Thank you for your feedback.
